import type { Product } from "./store-context"

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Leather Handbag",
    price: 28900,
    originalPrice: 35900,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&h=800&fit=crop",
    category: "accessories",
    rating: 4.8,
    reviews: 124,
    description: "Handcrafted from the finest Italian leather, this timeless handbag features a spacious interior with multiple compartments. Perfect for both work and weekend.",
    sizes: ["Small", "Medium", "Large"],
    colors: ["Black", "Brown", "Tan"],
    badge: "bestseller",
  },
  {
    id: "2",
    name: "Minimalist Watch Collection",
    price: 19500,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=800&fit=crop",
    category: "accessories",
    rating: 4.9,
    reviews: 89,
    description: "Elegant minimalist design with Swiss movement. Water-resistant up to 50m with a genuine leather strap.",
    colors: ["Silver", "Gold", "Rose Gold"],
    badge: "new",
  },
  {
    id: "3",
    name: "Cashmere Blend Sweater",
    price: 17500,
    originalPrice: 22000,
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&h=800&fit=crop",
    category: "women",
    rating: 4.7,
    reviews: 156,
    description: "Luxuriously soft cashmere blend sweater with a relaxed fit. Perfect for layering during cooler months.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream", "Gray", "Navy", "Burgundy"],
    badge: "sale",
  },
  {
    id: "4",
    name: "Classic White Sneakers",
    price: 12900,
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&h=800&fit=crop",
    category: "footwear",
    rating: 4.6,
    reviews: 203,
    description: "Clean, versatile sneakers crafted with premium materials. Cushioned insole for all-day comfort.",
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44"],
    colors: ["White", "Black", "Off-White"],
  },
  {
    id: "5",
    name: "Wireless Noise-Canceling Headphones",
    price: 34900,
    originalPrice: 39900,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=800&fit=crop",
    category: "electronics",
    rating: 4.9,
    reviews: 312,
    description: "Industry-leading noise cancellation with premium sound quality. 30-hour battery life.",
    colors: ["Matte Black", "Silver", "Midnight Blue"],
    badge: "sale",
  },
  {
    id: "6",
    name: "Linen Summer Dress",
    price: 14500,
    image: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&h=800&fit=crop",
    category: "women",
    rating: 4.5,
    reviews: 78,
    description: "Breathable linen dress perfect for warm summer days. Features a flattering A-line silhouette.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["White", "Sage", "Sand"],
    badge: "new",
  },
  {
    id: "7",
    name: "Tailored Wool Blazer",
    price: 42500,
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&h=800&fit=crop",
    category: "men",
    rating: 4.8,
    reviews: 67,
    description: "Expertly tailored blazer in premium wool. A wardrobe essential for the modern gentleman.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Charcoal", "Navy", "Black"],
    badge: "bestseller",
  },
  {
    id: "8",
    name: "Designer Sunglasses",
    price: 26500,
    originalPrice: 32000,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=800&fit=crop",
    category: "accessories",
    rating: 4.7,
    reviews: 145,
    description: "Timeless aviator design with UV400 protection and polarized lenses.",
    colors: ["Gold/Green", "Silver/Gray", "Black/Black"],
    badge: "sale",
  },
  {
    id: "9",
    name: "Ceramic Vase Set",
    price: 8900,
    image: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600&h=800&fit=crop",
    category: "home",
    rating: 4.6,
    reviews: 54,
    description: "Set of 3 handcrafted ceramic vases in complementary sizes. Perfect for modern interiors.",
    colors: ["White", "Terracotta", "Sage"],
  },
  {
    id: "10",
    name: "Running Performance Shoes",
    price: 18900,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=800&fit=crop",
    category: "footwear",
    rating: 4.8,
    reviews: 287,
    description: "Engineered for peak performance with responsive cushioning and breathable mesh upper.",
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    colors: ["Red/Black", "Blue/White", "Gray/Neon"],
    badge: "bestseller",
  },
  {
    id: "11",
    name: "Smart Home Speaker",
    price: 19900,
    image: "https://images.unsplash.com/photo-1589003077984-894e133dabab?w=600&h=800&fit=crop",
    category: "electronics",
    rating: 4.5,
    reviews: 198,
    description: "Premium sound in a compact design with voice assistant integration.",
    colors: ["Charcoal", "Chalk", "Coral"],
    badge: "new",
  },
  {
    id: "12",
    name: "Silk Scarf Collection",
    price: 12500,
    image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&h=800&fit=crop",
    category: "accessories",
    rating: 4.9,
    reviews: 92,
    description: "100% pure silk scarf with hand-rolled edges. Multiple ways to style.",
    colors: ["Floral", "Geometric", "Abstract"],
  },
]

export const brands = [
  {
    id: "1",
    name: "Luxora",
    logo: "https://images.unsplash.com/photo-1611339555312-e607c04352fa?w=200&h=80&fit=crop",
  },
  {
    id: "2",
    name: "StyleHub",
    logo: "https://images.unsplash.com/photo-1611339555312-e607c04352fa?w=200&h=80&fit=crop",
  },
  {
    id: "3",
    name: "ElegantWear",
    logo: "https://images.unsplash.com/photo-1611339555312-e607c04352fa?w=200&h=80&fit=crop",
  },
  {
    id: "4",
    name: "ModernClique",
    logo: "https://images.unsplash.com/photo-1611339555312-e607c04352fa?w=200&h=80&fit=crop",
  },
  {
    id: "5",
    name: "TrendSetters",
    logo: "https://images.unsplash.com/photo-1611339555312-e607c04352fa?w=200&h=80&fit=crop",
  },
  {
    id: "6",
    name: "ClassicStyle",
    logo: "https://images.unsplash.com/photo-1611339555312-e607c04352fa?w=200&h=80&fit=crop",
  },
]

export const testimonials = [
  {
    id: "1",
    name: "Sarah Mitchell",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    rating: 5,
    text: "Absolutely love the quality and attention to detail. The customer service is exceptional!",
    product: "Premium Leather Handbag",
  },
  {
    id: "2",
    name: "James Chen",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    rating: 5,
    text: "Best online shopping experience I&apos;ve had. Fast shipping and the products exceed expectations.",
    product: "Tailored Wool Blazer",
  },
  {
    id: "3",
    name: "Emma Wilson",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    rating: 5,
    text: "The cashmere sweater is incredibly soft. Will definitely be ordering more!",
    product: "Cashmere Blend Sweater",
  },
]

export const faqKeys = [
  { questionKey: "what_return_policy", answerKey: "return_policy_answer" },
  { questionKey: "how_long_shipping", answerKey: "shipping_time_answer" },
  { questionKey: "do_you_offer_cod", answerKey: "cod_answer" },
  { questionKey: "how_track_order", answerKey: "track_order_answer" },
  { questionKey: "payment_methods_accepted", answerKey: "payment_methods_answer" },
  { questionKey: "gift_wrapping", answerKey: "gift_wrapping_answer" },
  { questionKey: "how_know_size", answerKey: "size_guide_answer" },
  { questionKey: "cancel_modify_order", answerKey: "cancel_modify_answer" },
]

/** @deprecated Use faqKeys with useTranslation() instead */
export const faqs = faqKeys.map((k) => ({ question: k.questionKey, answer: k.answerKey }))

